# This is a auto generate menu.md file workflow
name: Auto Generate Menu

# Controls when the workflow will run
on:
  # 在 main 分支发生 push 时执行
  push:
    branches:
      - main
  # 通过定时任务执行
  schedule:
    - cron: "30 10,23 * * *"

jobs:
  # This workflow contains a single job called "update-menu-job"
  update-menu-job:
    name: Update this repo's source/menu/index.md file.
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # 1. 通过 actions/checkout action 获取项目源码
      - name: 'Checkout codes'
        uses: actions/checkout@master
      # 2. 部署 Golang 环境
      - name: 'Setup Go environment'
        uses: actions/setup-go@v4
        with:
          go-version: '1.16.15'
      # 3. 部署 Node.js 环境，并生成
      - name: 'Setup Node.js environment'
        uses: actions/setup-node@v3
        with:
          node-version: '16.2.0'
      # 4. check
      - name: 'Install and check software'
        run: |
          go version
          node -v
          npm -v
          rm -rf ./node_modules
          npm install -g hexo-cli
          npm install
          hexo --version
      # 5. 抓取博客标题，并覆盖 source/menu/index.md 文件
      - name: 'Crawler my blog title'
        run: |
          cd ./daily_auto_generate_menu
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o spider-blog-title spider_blog_title.go
          ./spider-blog-title
          cd ../
          rm -rf source/menu/index.md
          mv daily_auto_generate_menu/blog-menu.md source/menu/index.md
      - name: 'Build and deploy'
        run: |
          echo "auto generate menu"-`date +"%Y-%m-%d_%H:%M:%S"`